name: stale
on:
  schedule:
    - cron: "* * * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-close: 0
          close-issue-message: |
            This issue has been automatically closed. Please, open a discussion for bug reports and feature requests.
            
            Read more: [https://github.com/deployphp/deployer/discussions/3888]
          days-before-pr-stale: -1
          days-before-pr-close: -1
