name: sync

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run docgen
        run: php bin/docgen

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: 'docs'
          message: '[automatic] Update docs with bin/docgen'

